# Generated by Django 5.2.3 on 2025-06-25 09:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
                ('date_operation', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(default='Compte bancaire', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectDebit',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_frais.operation')),
                ('date_prelevement', models.DateField()),
                ('echeance', models.DateField(blank=True, default=None, null=True)),
                ('frequence', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel')], default='Mensuel', max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('my_frais.operation',),
        ),
        migrations.AddField(
            model_name='operation',
            name='compte_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='my_frais.account'),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
                ('date_premier_versement', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin optionnelle', null=True)),
                ('frequence', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel'), ('Hebdomadaire', 'Hebdomadaire')], default='Mensuel', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('type_revenu', models.CharField(choices=[('Salaire', 'Salaire'), ('Subvention', 'Subvention'), ('Aide', 'Aide'), ('Pension', 'Pension'), ('Loyer', 'Loyer perçu'), ('Autre', 'Autre')], default='Salaire', max_length=50)),
                ('compte_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_incomes', to='my_frais.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_projection', models.DateField()),
                ('periode_projection', models.IntegerField(help_text='Nombre de mois à projeter')),
                ('solde_initial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('projections_data', models.JSONField(help_text='Données des projections au format JSON')),
                ('compte_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_projections', to='my_frais.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('compte_reference', 'date_projection', 'periode_projection')},
            },
        ),
    ]
