# Generated by Django 5.2.3 on 2025-06-24 19:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_frais.basemodel')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=('my_frais.basemodel',),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_frais.basemodel')),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('my_frais.basemodel',),
        ),
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_frais.operation')),
                ('date_prelevement', models.DateField()),
                ('echeance', models.DateField(blank=True, default=None)),
            ],
            bases=('my_frais.operation',),
        ),
        migrations.AddField(
            model_name='operation',
            name='compte_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_frais.compte'),
        ),
    ]
