# Generated by Django 5.2.3 on 2025-06-24 22:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_frais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compte',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Prelevement',
            new_name='DirectDebit',
        ),
    ]
