# Generated by Django 5.2.3 on 2025-06-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_frais', '0002_taskexecution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskExecution',
        ),
    ]
