# Generated by Django 5.2.3 on 2025-06-30 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_frais', '0003_delete_taskexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('PAYMENT_PROCESSING', 'Traitement des prélèvements'), ('INCOME_PROCESSING', 'Traitement des revenus'), ('BOTH_PROCESSING', 'Traitement complet'), ('MANUAL_EXECUTION', 'Exécution manuelle')], max_length=50, verbose_name='Type de tâche')),
                ('execution_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'exécution")),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('ERROR', 'Erreur'), ('PARTIAL', 'Partiel')], max_length=20, verbose_name='Statut')),
                ('processed_count', models.IntegerField(default=0, verbose_name="Nombre d'opérations traitées")),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('execution_duration', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name="Durée d'exécution (secondes)")),
                ('details', models.JSONField(blank=True, default=dict, verbose_name="Détails de l'exécution")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche automatique',
                'verbose_name_plural': 'Tâches automatiques',
                'ordering': ['-execution_date'],
            },
        ),
    ]
