# Generated by Django 5.2.3 on 2025-06-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_frais', '0004_automatedtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automated_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
