# Generated by Django 5.2.3 on 2025-06-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_frais', '0006_alter_automatedtask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='source_automatic_id',
            field=models.CharField(blank=True, help_text='ID source pour éviter les doublons', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('direct_debit', 'Prélèvement automatique'), ('recurring_income', 'Revenu récurrent'), ('manual', 'Opération manuelle')], default='manual', max_length=20, null=True),
        ),
    ]
