# Generated by Django 5.2.3 on 2025-07-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_frais', '0007_add_operation_source_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
                ('date_transaction', models.DateField()),
                ('transaction_type', models.CharField(choices=[('direct_debit', 'Prélèvement automatique'), ('recurring_income', 'Revenu récurrent')], max_length=20)),
                ('source_id', models.CharField(help_text='ID source pour éviter les doublons', max_length=100)),
                ('source_reference', models.CharField(help_text='Référence de la source (DirectDebit.id ou RecurringIncome.id)', max_length=100)),
                ('processed', models.BooleanField(default=True, help_text='Indique si la transaction a été traitée')),
                ('compte_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_transactions', to='my_frais.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction automatique',
                'verbose_name_plural': 'Transactions automatiques',
                'ordering': ['-date_transaction', '-created_at'],
                'unique_together': {('source_id', 'transaction_type')},
            },
        ),
    ]
