name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Tests unitaires et de qualité
  test:
    runs-on: ubuntu-latest
    name: Tests et Qualité du Code

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mes_frais
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u test_user -ptest_password --protocol=tcp"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongodb:
        image: mongo:5.0
        env:
          MONGO_INITDB_ROOT_USERNAME: test_user
          MONGO_INITDB_ROOT_PASSWORD: test_password
          MONGO_INITDB_DATABASE: mes_frais_logs
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          # Installation de pymongo pour les tests de connectivité
          python3 -m pip install --user pymongo

      - name: Create and activate virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Wait for services to be ready
        run: |
          echo "Attente que les services soient prêts..."
          
          # Attendre MySQL
          echo "Test de connexion MySQL..."
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -P 3306 -u test_user -ptest_password -e "SELECT 1;" 2>/dev/null; then
              echo "✅ MySQL est prêt !"
              break
            fi
            echo "⏳ Attente MySQL... ($i/30)"
            sleep 2
          done
          
          # Attendre MongoDB (test avec Python/pymongo)
          echo "Test de connexion MongoDB..."
          for i in {1..20}; do
            if python3 -c "import pymongo; pymongo.MongoClient('mongodb://127.0.0.1:27017/', serverSelectionTimeoutMS=2000).admin.command('ping')" 2>/dev/null; then
              echo "✅ MongoDB est prêt !"
              break
            fi
            echo "⏳ Attente MongoDB... ($i/20)"
            sleep 3
          done

      - name: Check services
        run: |
          echo "Vérification finale des services..."
          netstat -tuln | grep :3306 || echo "MySQL port non trouvé"
          netstat -tuln | grep :27017 || echo "MongoDB port non trouvé"
          mysql -h 127.0.0.1 -P 3306 -u test_user -ptest_password -e "SELECT 'MySQL OK';"
          python3 -c "import pymongo; print('MongoDB OK:', pymongo.MongoClient('mongodb://127.0.0.1:27017/', serverSelectionTimeoutMS=2000).admin.command('ping'))"

      - name: Setup MySQL permissions for tests
        run: |
          echo "Configuration des permissions MySQL pour les tests..."
          # Connexion en tant que root pour accorder les permissions
          mysql -h 127.0.0.1 -P 3306 -u root -proot_password << 'EOF'
          GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%' WITH GRANT OPTION;
          GRANT CREATE ON *.* TO 'test_user'@'%';
          GRANT DROP ON *.* TO 'test_user'@'%';
          FLUSH PRIVILEGES;
          SHOW GRANTS FOR 'test_user'@'%';
          EOF
          
          echo "Test de création de base de données par test_user:"
          mysql -h 127.0.0.1 -P 3306 -u test_user -ptest_password -e "CREATE DATABASE IF NOT EXISTS test_verification; DROP DATABASE test_verification; SELECT 'Permissions OK' AS status;"

      - name: Debug database connection
        env:
          SECRET_KEY: test-secret-key-for-github-actions
          DB_NAME: mes_frais
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          MONGODB_HOST: 127.0.0.1
          MONGODB_PORT: 27017
          MONGODB_DATABASE: mes_frais_logs
          MONGODB_USERNAME: test_user
          MONGODB_PASSWORD: test_password
          MONGODB_AUTH_SOURCE: admin
        run: |
          echo "Variables d'environnement pour Django:"
          echo "DB_HOST: $DB_HOST"
          echo "DB_PORT: $DB_PORT"
          echo "DB_NAME: $DB_NAME"
          echo "DB_USER: $DB_USER"
          
          echo "Test final de connectivité MySQL avec les mêmes paramètres:"
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASSWORD -e "SHOW DATABASES;" || echo "❌ Échec connexion MySQL"

      - name: Run migrations
        env:
          SECRET_KEY: test-secret-key-for-github-actions
          DB_NAME: mes_frais
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          MONGODB_HOST: 127.0.0.1
          MONGODB_PORT: 27017
          MONGODB_DATABASE: mes_frais_logs
          MONGODB_USERNAME: test_user
          MONGODB_PASSWORD: test_password
          MONGODB_AUTH_SOURCE: admin
        run: |
          source venv/bin/activate
          python manage.py migrate --noinput

      - name: Run tests
        env:
          SECRET_KEY: test-secret-key-for-github-actions
          DB_NAME: mes_frais
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          MONGODB_HOST: 127.0.0.1
          MONGODB_PORT: 27017
          MONGODB_DATABASE: mes_frais_logs
          MONGODB_USERNAME: test_user
          MONGODB_PASSWORD: test_password
          MONGODB_AUTH_SOURCE: admin
        run: |
          source venv/bin/activate
          python manage.py test

  # Job 2: Build et validation du code
  build:
    runs-on: ubuntu-latest
    name: Build et Collecte des Assets
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create and activate virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Collect static files
        env:
          SECRET_KEY: test-secret-key-for-github-actions
          DB_NAME: ":memory:"
          DB_USER: ""
          DB_PASSWORD: ""
          DB_HOST: ""
          DB_PORT: ""
          MONGODB_HOST: 127.0.0.1
          MONGODB_PORT: 27017
          MONGODB_DATABASE: mes_frais_logs
          MONGODB_USERNAME: ""
          MONGODB_PASSWORD: ""
          MONGODB_AUTH_SOURCE: ""
        run: |
          source venv/bin/activate
          # Utiliser SQLite en mémoire pour collectstatic (pas besoin de MySQL)
          python manage.py collectstatic --noinput --settings=core.settings_static

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            static/
            venv/
          key: ${{ runner.os }}-build-${{ github.sha }}

  # Job 3: Déploiement sur le serveur
  deploy:
    runs-on: ubuntu-latest
    name: Déploiement en Production
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/deploy_key $SERVER_USER@$SERVER_IP << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            source ${{ secrets.VENV_PATH }}/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            
            # Redémarrer le service directement
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S /usr/bin/systemctl restart ${{ secrets.SERVICE_NAME }}
            sleep 5
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S /usr/bin/systemctl status ${{ secrets.SERVICE_NAME }} --no-pager
          EOF

  # Job 4: Notification complète du pipeline CI/CD
  notify:
    runs-on: ubuntu-latest
    name: Notification du Pipeline CI/CD
    needs: [test, build, deploy]
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Generate notification content
        id: notification
        run: |
          # Générer le contenu de la notification
          NOTIFICATION_CONTENT="🚀 === RAPPORT DU PIPELINE CI/CD ===
          📋 Commit: ${{ github.sha }}
          👤 Auteur: ${{ github.actor }}
          📅 Date: $(date '+%Y-%m-%d %H:%M:%S UTC')
          
          "
          
          # Statut des tests
          if [ "${{ needs.test.result }}" == "success" ]; then
            NOTIFICATION_CONTENT+="✅ TESTS: Réussis
            - Tous les tests unitaires ont passé
            - Qualité du code validée
            "
          elif [ "${{ needs.test.result }}" == "failure" ]; then
            NOTIFICATION_CONTENT+="❌ TESTS: Échec
            - Certains tests ont échoué
            - Vérifiez les logs des tests
            "
          elif [ "${{ needs.test.result }}" == "cancelled" ]; then
            NOTIFICATION_CONTENT+="⚠️  TESTS: Annulés
            - Les tests ont été annulés
            "
          else
            NOTIFICATION_CONTENT+="❓ TESTS: Statut inconnu (${{ needs.test.result }})
            "
          fi
          
          # Statut du build
          if [ "${{ needs.build.result }}" == "success" ]; then
            NOTIFICATION_CONTENT+="✅ BUILD: Réussi
            - Assets collectés avec succès
            - Application prête pour le déploiement
            "
          elif [ "${{ needs.build.result }}" == "failure" ]; then
            NOTIFICATION_CONTENT+="❌ BUILD: Échec
            - Erreur lors de la collecte des assets
            - Vérifiez les logs du build
            "
          elif [ "${{ needs.build.result }}" == "cancelled" ]; then
            NOTIFICATION_CONTENT+="⚠️  BUILD: Annulé
            - Le build a été annulé
            "
          else
            NOTIFICATION_CONTENT+="❓ BUILD: Statut inconnu (${{ needs.build.result }})
            "
          fi
          
          # Statut du déploiement
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            NOTIFICATION_CONTENT+="✅ DÉPLOIEMENT: Réussi
            - Application déployée en production
            - Service redémarré avec succès
            - Mise à jour terminée
            "
          elif [ "${{ needs.deploy.result }}" == "failure" ]; then
            NOTIFICATION_CONTENT+="❌ DÉPLOIEMENT: Échec
            - Erreur lors du déploiement
            - Vérifiez les logs de déploiement
            "
          elif [ "${{ needs.deploy.result }}" == "cancelled" ]; then
            NOTIFICATION_CONTENT+="⚠️  DÉPLOIEMENT: Annulé
            - Le déploiement a été annulé
            "
          else
            NOTIFICATION_CONTENT+="❓ DÉPLOIEMENT: Statut inconnu (${{ needs.deploy.result }})
            "
          fi
          
          # Résumé global
          if [ "${{ needs.test.result }}" == "success" ] && [ "${{ needs.build.result }}" == "success" ] && [ "${{ needs.deploy.result }}" == "success" ]; then
            NOTIFICATION_CONTENT+="🎉 === DÉPLOIEMENT COMPLET RÉUSSI ===
            Tous les étapes du pipeline ont été exécutées avec succès !
            L'application est maintenant en production.
            "
            SUBJECT="✅ Déploiement réussi - Mes Frais"
          else
            NOTIFICATION_CONTENT+="⚠️  === PROBLÈME DÉTECTÉ ===
            Au moins une étape du pipeline a échoué.
            Vérifiez les logs pour plus de détails.
            "
            SUBJECT="❌ Échec du pipeline CI/CD - Mes Frais"
          fi
          
          NOTIFICATION_CONTENT+="
          🔗 Voir les détails: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          # Sauvegarder dans des variables d'output
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTIFICATION_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "subject=$SUBJECT" >> $GITHUB_OUTPUT
          
          # Afficher dans les logs aussi
          echo "$NOTIFICATION_CONTENT"

      - name: Create deployment status comment
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              per_page: 1
            });
            
            const commit = commits[0];
            const status = '${{ needs.test.result }}' === 'success' && 
                          '${{ needs.build.result }}' === 'success' && 
                          '${{ needs.deploy.result }}' === 'success' ? '✅' : '❌';
            
            const subject = '${{ steps.notification.outputs.subject }}';
            const content = `${{ steps.notification.outputs.content }}`;
            
            const comment = `## ${subject}

            ${content}

            ---
            *Notification automatique du pipeline CI/CD*`;
            
            try {
              await github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha,
                body: comment
              });
              console.log('✅ Commentaire de statut ajouté au commit');
            } catch (error) {
              console.log('⚠️ Impossible d\'ajouter le commentaire:', error.message);
            }

      - name: Create deployment summary
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const isSuccess = '${{ needs.test.result }}' === 'success' && 
                             '${{ needs.build.result }}' === 'success' && 
                             '${{ needs.deploy.result }}' === 'success';
            
            const summary = `## 🚀 Résumé du Déploiement

            **Statut:** ${isSuccess ? '✅ Succès' : '❌ Échec'}
            **Commit:** \`${{ github.sha }}\`
            **Auteur:** ${{ github.actor }}
            **Date:** ${new Date().toLocaleString('fr-FR')}

            ### 📊 Détails des étapes:
            - **Tests:** ${{ needs.test.result == 'success' && '✅' || '❌' }} ${{ needs.test.result }}
            - **Build:** ${{ needs.build.result == 'success' && '✅' || '❌' }} ${{ needs.build.result }}
            - **Déploiement:** ${{ needs.deploy.result == 'success' && '✅' || '❌' }} ${{ needs.deploy.result }}

            🔗 [Voir les logs complets](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            try {
              // Créer un commentaire sur le commit
              await github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha,
                body: summary
              });
              
              // Si c'est un succès, créer aussi un commentaire sur le dernier commit
              if (isSuccess) {
                console.log('🎉 Déploiement réussi - Notification ajoutée au commit');
              } else {
                console.log('⚠️ Déploiement échoué - Notification d\'erreur ajoutée');
              }
            } catch (error) {
              console.log('⚠️ Erreur lors de l\'ajout du commentaire:', error.message);
            }

      - name: Log notification status
        if: always()
        run: |
          echo "📧 === STATUT DES NOTIFICATIONS ==="
          echo "✅ Notifications GitHub natives activées"
          echo "   - Commentaires sur les commits"
          echo "   - Résumés de déploiement"
          echo "   - Logs détaillés dans GitHub Actions"
          
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "✅ Commentaire de statut ajouté au commit"
          else
            echo "ℹ️  Commentaire de commit non ajouté (pas un push sur main)"
          fi
          
          echo ""
          echo "🔗 Voir les détails: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"